### ISSUE TITLE
Choose a Python package manager

### ISSUE THREAD

**Issue by michaelconnor00** [sparkgeo/mountaineer#3]
Project in Python should use a package manager to manage dependencies in a project. There are a bunch to choose from, it is a confusing space. Here are some to consider:

- Pipenv
- Poetry
- Conda
- Pyenv
- Standard Pip

There are pros and cons to each. Read their descriptions.

**Comment by AL-SparkGeo** [comment]
Standard Pip: Package installer that uses commands to install packages and libraries into the PATH of the file system. Due to a lack of virtual environments, this direct use is not encouraged, as libraries and packages with differing or similar names can muck up the PATH and cause development headaches down the road. Creating virtual environments keeps these variables separate, and won't be installed directly to the PATH. **Probably won't be used due to lack of VENV support.**

Pipenv: Folder-level dependency manager for pip. Dependences are installed on a per-folder basis, and aren't put into the "main" system environment. This isolates them from the path and prevents errors from happening when there are packages or libraries that share names and dependencies. **Could be used as an alternative to pipenv, although it does NOT have a simple packaging proces like Poetry does.**

Poetry: All-in-one package and virtual environment manager. Automates creation of python project folder, creates init.py and lists of dependencies in a .yoml file. Also enables for creation of packages upon software completion, and will handle installing dependencies in virtual environments. Dependencies are written to a lock file, that can be used to share and distribute the package, which is created automatically as more dependencies are installed. **This is probably the best choice for a simple project.**

Conda: Data-science based VENV and package manager. Special in that it is not python specific and is designed to handle environments better than packages, and has support for other programming languages, not restricted to Python. Can be used to set up virtual environments and jupyter notebooks, along with other data-science tools. **Might be good for larger data-science and data visualization projects, but not necessarily for managing Python packages.**

Pyenv: Not a package manager but a Python version manager. Used to switch between Python 2.x and Python 3.x, and other versions in between. Can be set as an environment variable to ensure package runs under correct python version. **Not a package manager.**

**Comment by AL-SparkGeo** [comment]
All signs seem to be pointing to **Poetry** as the ideal package manager for a project like this. Poetry acts as a sort of all-in-one tool, for both creating virtual environments and also creating packages. Pipenv for example does not have a simple packaging process, Standard PIP is too intrusive onto the system path, and Conda, while it is a useful tool, might be better suited for a Jupyter notebook. Perhaps Conda and Jupyter could be managed later on in development as a means to display the data using pandas, but as of this moment, its use as a package manager might not be the best option out of these.

Simply because **Poetry** simplifies the packaging and environment process, it stands above the rest. It is also a relatively new tool, and it might be better to work with something more on the bleeding/cutting edge than something older, especially for a new project and because SparkGeo is all about new tech.

**Comment by michaelconnor00** [comment]
Yes. All your comments about Poetry and the same as mine. Please proceed with implimenting Poetry in this project.

**Comment by michaelconnor00** [comment]
Tag me on the PR when it is done.
