### ISSUE TITLE
Choose a CLI framework

### ISSUE THREAD

**Issue by michaelconnor00** [sparkgeo/mountaineer#4]
When building CLI frameworks, there are a few great options. Using the standard library tools such as `sys.argv` is fine for the most simple cases, but when buildling a CLI, you will want more features. Some examples of frameworks are:

- Click
- Typer
- Docopt

There could be more. Have a look and read some docs. Choose the one that looks like it will be a good fit.

**Comment by AL-SparkGeo** [comment]
Typer: Fast and simple CLI that requires Python 3.6+. and uses Click as a dependency. Designed to be easy to use and simple, even simpler than click. Due to the way that it's structured, it can still work even in incomplete libraries. Allows nesting of commands just like Click, allowing us to create subcommands if needed. Helps create robust help pages without much user-input, and is less customizable as a result, due to it's dependency on Click. **This is probably the best option for a simple project.**

Click:  CLI that relies on nested commands. It allows for rigid yet flexible CLI that lets you have robust help options. Separate from optparse and argparse in that it doesn't have typing issues. Simpler to use than both optparse and argparse, but more complicated than Typer. Automatically handles creation of help and organizes it outside of the user, so they don't need to look at it more often. **2nd Best Option, might work better for larger projects**

Docopt: More-complex CLI that requires the CLI to be typed out beforehand, and defined by the writer. If used to create a help page, the help page can be more customized and edited by the user, and isn't as strict or rigid as Typer and Click. This could create a problem where Docopt could be more robust but could also be prone to unclear user-documentation when used by amateur or inexperienced documenters. Similar to **Argparse**, which also relies on a strongly user-defined  help documentation. **Least user friendly, even though it can be customized more than Click and Typer.**

**Comment by AL-SparkGeo** [comment]
Through my research, I suspect a simple CLI would be all that I need for a project like this. As it is relatively small scale deployment and scaling wise, I do not suspect extensive help documentation that needs to be hand-written is required. By this reasoning, both Typer and Click are more immediately appealing than Docopt and Argparse. However, should the project grow in scope, it might be worth allowing room for more customizable CLI input. This would make both Docopt and Argparse useful, but immediately, I feel they could be more of a hindrance than a help.

I was hoping to try out Typer, as it seems relatively light weight and user friendly. How does this sound?

**Comment by michaelconnor00** [comment]
Yes, Typer is a great option. 

I would argue that Docopt is the easiest CLI tool, but the most limited. Feel free to give it a try. But only if you have time.

**Comment by michaelconnor00** [comment]
Tag me on a PR when you get it complete.
